### ISSUE TITLE
请问这个支持打包成app吗？

### ISSUE THREAD

**Issue by wookkkkk** [welives/taro-react-starter#1]
另外，项目的开源协议是什么？
我是个新手，刚学taro，想找个框架跟着学学做些项目

**Comment by welives** [comment]
支持的，因为用的UI框架是京东自家基于Taro的，你不喜欢的话就卸载掉换其他基于Taro的跨端UI框架

**Comment by welives** [comment]
> 另外，项目的开源协议是什么？ 我是个新手，刚学taro，想找个框架跟着学学做些项目

支持的，因为用的UI框架是京东自家基于Taro的，你不喜欢的话就卸载掉换其他基于Taro的跨端UI框架

**Comment by wookkkkk** [comment]
谢谢答复，这两天也看了下taro和nutui的说明，好像端和小程序引入的nutui是不同的，现在也没搞太懂，我继续学习下
