### ISSUE TITLE
初次启动报错，{"errMsg":"reLaunch:fail page \"pages/blank/pages/index/index?\" is not found"}

### ISSUE THREAD

**Issue by xiaoxianBoy** [welives/taro-react-starter#2]
![image](https://github.com/welives/taro-react-starter/assets/22361503/b364676b-66b8-4682-91fd-7321084f43db)

taro ：3.6.18

**Comment by xiaoxianBoy** [comment]
大佬，是什么地方配置不对吗？

**Comment by welives** [comment]
> 大佬，是什么地方配置不对吗？

你配置的页面路径不存在,你确定不是应该配置成 pages/blank/index 吗

**Comment by welives** [comment]
> 大佬，是什么地方配置不对吗？

代码已更新,是路由封装的时候没让路径以 / 开头导致, taro的路由跳转强制要求传入的url要以 / 开头

**Comment by xiaoxianBoy** [comment]
感谢大佬🙏
