### ISSUE TITLE
微信小程序真机调试或者预览时会出现home页面闪烁

### ISSUE THREAD

**Issue by wozzup** [welives/taro-react-starter#5]
微信开发者工具打开此项目，选择真机调试，在 `blank` 页面 `useLoad` 逻辑中 `router.reLaunch({ url: '/pages/index/index' })` 这里 `reLaunch` 到 `index` 页面的时候微信小程序会把 `home` 页面先显示出来（闪现、闪烁）然后再到 `index` 页面

**Comment by welives** [comment]
> 微信开发者工具打开此项目，选择真机调试，在 `blank` 页面 `useLoad` 逻辑中 `router.reLaunch({ url: '/pages/index/index' })` 这里 `reLaunch` 到 `index` 页面的时候微信小程序会把 `home` 页面先显示出来（闪现、闪烁）然后再到 `index` 页面

我在自己的iPhone 13 mini 上真机预览时没这问题
