### ISSUE TITLE
请问 tabbar iconPath icon.png 用的是什么系列的图标呀

### ISSUE THREAD

**Issue by wozzup** [welives/taro-react-starter#6]
tabbar选的很有眼光，审美在线，我想在这个基础上加几个tabbar图标，请问这个图标是什么系列或者名称或者包的呢？多谢哦

**Comment by welives** [comment]
> tabbar选的很有眼光，审美在线，我想在这个基础上加几个tabbar图标，请问这个图标是什么系列或者名称或者包的呢？多谢哦

不是网上的免费图标，是从我以前项目里随便拿几个来用的，公司UI自己画的

**Comment by wozzup** [comment]
cool 多谢回复 节日快乐
